name: 'Setup Python with Poetry'
description: 'Setup Python with Poetry'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.10'
runs:
  using: 'composite'
  steps:
    - name: 'Setup Python'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: 'Install Poetry'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
    - name: Install dependencies
      shell: bash
      run: poetry install --no-interaction