name: CI
on:
  push:
    branches: [ '**', '!main' ]

jobs:
  # ----------------------------------------------------------------
  # 1) Code Quality (Ruff / pre-commit) lint, format, pyright checks
  # ----------------------------------------------------------------
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup uv
        uses: ./.github/actions/setup-uv

      - name: pre-commit code quality checks
        run: uvx pre-commit run
  
  # ----------------------------------------------------------------
  # 2) Run pytest unit tests
  # ----------------------------------------------------------------
  pytest:
    runs-on: ubuntu-latest
    needs: [ruff]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup uv
        uses: ./.github/actions/setup-uv

      - name: Create a new virtual environment
        run: uv venv

      - name: install package
        run: uv pip install .

      - name: Run pytest
        run: uv run pytest -v --durations=0 --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}