name: CI
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  ruff-lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Python version
        id: python-version
        run: |
          echo "version=$(head -n 1 .python-versions)" >> $GITHUB_OUTPUT

      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ steps.python-version.outputs.version }}

      - name: Run tests
        run: poetry run pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest
    needs: [ruff-lint-and-format]
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(steps.get-test-versions.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get test versions
        id: get-test-versions
        run: |
          echo "matrix=$(cat .python-versions | jq -R -s -c 'split("\n")')" >> $GITHUB_OUTPUT


      - name: Setup Python with Poetry
        uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: poetry run pytest -v --durations=0 --cov --cov-report=xml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

