name: Tag on Merge to Main

on:
    pull_request:
        branches:
            - main  # Adjust the branch name as needed
        types: [closed]

jobs:
  tag_release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Python with Poetry
          uses: ./.github/actions/setup-python-poetry
          with:
            python-version: '3.10'

        - name: Configure Git
          run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "github-actions[bot]"

        - name: Get Version
          run: |
            VERSION=$(poetry version | cut -d' ' -f2)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Check if tag already exists
          id: check_tag
          run: |
            if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
              echo "::error::Tag v${VERSION} already exists on GitHub. Please bump the version in pyproject.toml."
              exit 1
            fi

        - name: Create and push new tag
          if: success()
          run: |
            git tag -a "v${VERSION}" -m "Automated release version v${VERSION}"
            git push origin "v${VERSION}"
